FROM moinfar/bio-deep-python:tensorflow-py36

COPY installer-gpu.sh /tmp/installer-gpu.sh
RUN sh /tmp/installer-gpu.sh && \
    rm /tmp/installer-gpu.sh && \
    mkdir /app/

COPY runner.sh /app/runner.sh
COPY tsv_to_csv.py /app/tsv_to_csv.py
COPY time_it.sh /time_it.sh

WORKDIR /app
ENTRYPOINT ["bash", "runner.sh"]
