FROM moinfar/bio-deep-python:tensorflow-py36

COPY installer-gpu.sh /tmp/installer-gpu.sh
RUN sh /tmp/installer-gpu.sh && \
    rm /tmp/installer-gpu.sh

COPY runner.sh /app/runner.sh
COPY transpose_it.py /app/transpose_it.py

WORKDIR /app
ENTRYPOINT ["bash", "runner.sh"]
